name: Generate Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: <your-github-username>
          template: classic
          base: header, activity, community
          plugin_isocalendar: 'yes'
          plugin_isocalendar_duration: 'full-year'
          # Ensure output filename here if you're outputting as an image
          filename: metrics.plugin.isocalendar.svg
